// Esto es gracias a la extension q descargamos de visual Rest HTTP

### Recuperar todas las pelis
GET http://localhost:1234/movies


### Recuperar una pelicula x ID
//GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

## Recuperar todas las peliculas por un genero (x query params)
//GET http://localhost:1234/movies?genre=action  

POST http://localhost:1234/movies
Content-Type: application/json

{ // Nuestras APIs tienen q eestar abiertas a todo, exquisitas en lo qeue procesan 
  "sql": "SELECT * FROM users", 
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula

PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  //"id": "123", // el ID no se puede cambiar porque el ID no se esta validando en el zod
  "title" : "HOLA",
  "year" : 1993
}